# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6e16f78840e46c7fd1f98684c79278fa7ac0474776c2e3ce3a71a13ec009034226956d74ece6025047077e1f73abb2787c1aef5cb22d3d7ff74a0c0c444dfa30

test:
  secret_key_base: 01acb5851d43b39d3a513eff2c75356da5d91f44beb50cd514dbf777ea2c0e6c468433de66dca672cbc36cb13ade1187a310fc72e3283c6fc1cd18e4eac9c8e8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
